org.gradle.jvmargs = -Xmx2G

# Mod Info
mod_version = 1.0.0a
mod_id = just_sink
mod_name = JustSink
mod_authors = ZhanMing
mod_description = Just sink
mod_license = BSD 3-Clause (NewBSD) License
mod_group_id = com.github.zhan6ming

# Minecraft
minecraft_version = 1.16.5
minecraft_version_range = [1.16.5,1.17)

# Forge
forge_version = 36.2.39
forge_version_range = [36,)
loader_version_range = [36,)
