org.gradle.jvmargs = -Xmx2G
org.gradle.daemon = true
org.gradle.parallel = true
org.gradle.caching = true
org.gradle.configuration-cache = false

# Mod Info
mod_version = 1.1.5
mod_id = just_sink
mod_name = JustSink
mod_authors = ZhanMing
mod_description = Just added a sink
mod_license = BSD-3-Clause
mod_group_id = com.github.zhan6ming
source_url = https://github.com/Zhan6Ming/JustSink
issue_tracker_url = https://github.com/Zhan6Ming/JustSink/issues

# Minecraft
minecraft_version = 1.20.1
yarn_mappings = 1.20.1+build.10

# Fabric
# https://fabricmc.net/develop/
loader_version = 0.19.3
loom_version = 1.10.+

# Fabric API
fabric_api_version = 0.92.11+1.20.1
